name: Build

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore src/fdc3-dotnet.sln

    - name: Build
      run: dotnet build src/fdc3-dotnet.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test src/fdc3-dotnet.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --configuration Release

    - name: Pack Fdc3
      run:
        dotnet pack src/Fdc3/Finos.Fdc3.csproj --no-build --configuration Release --output packages

    - name: Pack Fdc3.NewtonsoftJson
      run:
        dotnet pack src/Fdc3.NewtonsoftJson/Finos.Fdc3.NewtonsoftJson.csproj --no-build --configuration Release --output packages
        
    - name: Pack Fdc3.Json
      run:
        dotnet pack src/Fdc3.Json/Finos.Fdc3.Json.csproj --no-build --configuration Release --output packages        

    - name: Pack Fdc3.AppDirectory
      run:
        dotnet pack src/Fdc3.AppDirectory/Finos.Fdc3.AppDirectory.csproj --no-build --configuration Release --output packages

    - name: Upload
      uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
      with:
        name: package
        path: packages/*.nupkg
        if-no-files-found: error

    - name: Codecov
      uses: codecov/codecov-action@13ce06bfc6bbe3ecf90edbbf1bc32fe5978ca1d3 # v5.3.1
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}