name: CVE Scanning

on:
  push:
  workflow_dispatch:

jobs:
  dotnet-modules-scan:
    name: dotnet-scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build project with dotnet
        run: dotnet build --configuration Release
        working-directory: 'src'
      - name: List vulnerable libraries
        run: dotnet list package --vulnerable --include-transitive
        working-directory: 'src'
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@3102a65fd5f36d0000297576acc56a475b0de98d
        id: Depcheck
        with:
          project: '.'
          path: '.'
          format: 'HTML'
          out: 'reports'
          args: >
            --suppression .cve/allow-list.xml
            --failOnCVSS 7
            --enableRetired
      - name: Upload Test results
        if: ${{ always() }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: Depcheck report
          path: ${{ github.workspace }}/reports
