name: License Scanning

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-modules-scan:
    name: dotnet-scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup .NET
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
        with:
          dotnet-version: 8.x
      - name: Build project with dotnet
        run: dotnet build --configuration Release
        working-directory: 'src'
      - name: Install nuget-license
        run: dotnet tool install --global nuget-license --version 3.1.3
        working-directory: 'src'
      - name: run nuget license
        run: nuget-license -i fdc3-dotnet.sln --allowed-license-types ../.license/allowed-licenses.json --output JsonPretty --error-only -exclude-projects ../.license/excluded-projects.json -mapping ../.license/license-mapping.json
        working-directory: 'src'
