name: License Scanning

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  dotnet-modules-scan:
    name: dotnet-scan
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build project with dotnet
        run: dotnet build --configuration Release
        working-directory: 'src'
      - name: Install dotnet-project-license
        run: dotnet tool install --global dotnet-project-licenses --version 2.7.1
        working-directory: 'src'
      - name: run dotnet-project-licenses
        run: dotnet-project-licenses -i . --allowed-license-types ../.license/allowed-licenses.json
        working-directory: 'src'
